- ruleID: register-apis
  description:  |
    API exposed by microservice
    This REST controller exposes an api, it needs to be registered.
  category: mandatory
  effort: 10
  labels:
    - "konveyor.io/target=cloud-readiness"
  when:
    or:
    - java.referenced:
        pattern: "java.nio.file.Paths.get({*})"
        location: "METHOD_CALL"
  message: "REST Controller found, did you register this in the firewall for ARO?"
  tag:
    - "3rd party=Apache Aries"
