- ruleID: sal-test
  labels:
    - "konveyor.io/target=cloud-readiness"
  when:
    java.referenced:
      pattern: "io.konveyor.demo.config.ApplicationConfiguration"
      location: "VARIABLE_DECLARATION"
  message: "MATCHED!!!!!!!"
  tag:
    - "3rd party=Apache Aries"
    - "testing my rules match"
